export const languagePresets: Record<string, Record<string, string>> = {
  pt: {
    'auth.welcome_back': 'Bem-vindo de volta!',
    'auth.subtitle': 'Acesse sua área exclusiva',
    'auth.login': 'Entrar',
    'auth.email': 'E-mail',
    'auth.password': 'Senha',
    'auth.restricted_access': 'Aviso de Acesso Restrito',
    'auth.restricted_access_msg': 'Acesso restrito a usuários cadastrados.',
    'auth.logout_success': 'Até logo!',
    'auth.master_password': 'Master Password',
    'auth.support_box': 'Precisa de Suporte?',
    'auth.support_description': 'Nossa equipe está pronta para te ajudar com qualquer dúvida ou problema técnico.',
    'auth.whatsapp_label': 'WhatsApp',
    'auth.email_label': 'E-mail',
    'auth.user_not_found': 'Usuário não encontrado',
    'auth.invalid_password': 'Senha incorreta. Verifique e tente novamente.',
    'auth.fill_this_field': 'Por favor, preencha este campo',
    'auth.invalid_email': 'Por favor, digite um endereço de e-mail válido',
    'auth.invalid_response': 'Falha na comunicação com o servidor. Tente novamente em instantes.',
    'auth.credentials_error': 'Falha ao gerar credenciais de acesso',
    'auth.generic_error': 'Ocorreu um erro. Tente novamente.',
    'auth.verify_access': 'Verificar Acesso',
    'auth.admin_identified': 'Identificamos um acesso administrativo. Por favor, insira a senha mestre para continuar.',
    'auth.disclaimer': 'Ao entrar, você concorda com nossos Termos de Uso e Política de Privacidade.',
    'global.logout_error': 'Erro ao sair da conta',
    'global.logging_out': 'Saindo da conta...',
    'global.session_lost': 'Sessão perdida. Reiniciando...',
    'profile.update_error': 'Erro ao atualizar perfil',
    'profile.avatar_error': 'Erro ao enviar foto de perfil',
    'profile.password_error': 'Erro ao atualizar senha',
    'dashboard.loading_error': 'Erro ao carregar conteúdos',
    'course.purchase_unavailable': 'Este curso ainda não possui um link de compra configurado.',
    'course.not_found': 'Curso não encontrado',
    'course.loading_error': 'Erro ao carregar curso',
    'course.progress_error': 'Erro ao atualizar progresso',
    'course.module': 'Módulo',
    'course.video_lesson': 'Videoaula',
    'course.pdf_material': 'Material PDF',
    'course.reading': 'Leitura',
    'course.view_fullscreen': 'Ver em Tela Cheia',
    'push.new_notification': 'Nova Notificação',
    'nav.home': 'Início',
    'nav.community': 'Comunidade',
    'nav.profile': 'Perfil',
    'nav.admin': 'Admin',
    'global.save': 'Salvar',
    'global.cancel': 'Cancelar',
    'global.delete': 'Excluir',
    'global.back': 'Voltar',
    'global.logout': 'Sair',
    'dashboard.courses_paid': 'Meus Cursos  📚',
    'dashboard.courses_free': 'Acelere sua Evolução  🚀',
    'dashboard.courses_bonus': 'Meus Bônus  🎁',
    'course.progress': 'Seu Progresso',
    'course.your_progress': 'Seu Progresso',
    'course.lessons': 'Aulas',
    'course.content': 'Conteúdo',
    'course.no_media': 'Aula sem conteúdo de mídia',
    'course.lesson_completed': 'Lesson completed!',
    'course.progress_saved': 'Your progress has been saved successfully.',
    'course.prev_lesson': 'Aula Anterior',
    'course.next_lesson': 'Próxima Aula',
    'course.materials': 'Materiais',
    'course.lesson_unmarked': 'Aula marcada como não concluída',
    'course.lesson_completed_btn': 'AULA CONCLUÍDA',
    'course.complete_lesson_btn': 'CONCLUIR AULA',
    'course.end_label': 'Fim',
    'course.support_description': 'Nossa equipe está pronta para te ajudar.',
    'course.premium_content': 'CONTEÚDO PREMIUM',
    'course.unlock_button': 'LIBERAR ACESSO AGORA',
    'course.secure_payment': 'Pagamento 100% Seguro • Acesso Imediato',
    'course.schedule_title': 'Cronograma do Curso',
    'course.completed': 'CONCLUÍDO',
    'course.continue': 'CONTINUAR',
    'course.start': 'COMEÇAR',
    'community.title': 'Comunidade',
    'community.subtitle': 'Compartilhe sua jornada',
    'community.input_placeholder': 'O que você quer compartilhar?',
    'community.post': 'Publicar',
    'community.send_reply': 'Enviar Resposta',
    'community.reply': 'Responder',
    'community.replying_to': 'Em resposta a',
    'community.like': 'Curtir',
    'community.delete_post': 'Excluir Post',
    'community.add_photo': 'Adicionar foto',
    'community.post_sent': 'Post enviado!',
    'community.post_updated': 'Post atualizado!',
    'community.edit_post': 'Editar Publicação',
    'community.delete_post_confirm': 'Excluir Publicação?',
    'community.delete_comment_confirm': 'Excluir Comentário?',
    'community.comment_placeholder': 'Escreva um comentário...',
    'community.delete_post_desc': 'Esta ação não pode ser desfeita. A publicação e sua imagem serão removidas permanentemente.',
    'community.delete_comment_desc': 'O comentário será removido permanentemente.',
    'community.delete_success': 'Publicação excluída com sucesso!',
    'community.delete_error': 'Erro ao excluir publicação',
    'community.load_error': 'Erro ao carregar publicações',
    'community.create_error': 'Erro ao enviar publicação',
    'community.update_error': 'Erro ao atualizar publicação',
    'community.upload_error': 'Não foi possível enviar a foto. Verifique sua conexão.',
    'community.comment_error': 'Erro ao enviar comentário',
    'community.comment_delete_success': 'Comentário excluído com sucesso!',
    'community.comment_delete_error': 'Erro ao excluir comentário',
    'community.date_format': "d 'de' MMM, HH:mm",
    'community.locale': 'ptBR',
    'community.load_more': 'Carregar mais publicações',
    'community.loading_posts': 'Carregando publicações...',
    'profile.title': 'Meu Perfil',
    'profile.subtitle': 'Gerencie suas informações',
    'profile.save_changes': 'Salvar Alterações',
    'profile.change_password': 'Alterar Senha',
    'profile.update_success': 'Perfil atualizado com sucesso!',
    'profile.avatar_success': 'Foto de perfil atualizada!',
    'profile.password_mismatch': 'As senhas não coincidem',
    'profile.password_success': 'Senha atualizada com sucesso!',
    'profile.change_photo': 'Trocar foto',
    'profile.info_title': 'Informações do Usuário',
    'profile.access': 'Acesso',
    'profile.email_restricted': 'O e-mail não pode ser alterado.',
    'profile.name_label': 'Nome',
    'profile.name_placeholder': 'Seu nome',
    'profile.phone_label': 'Telefone (WhatsApp)',
    'profile.phone_country_code': 'Código do país',
    'profile.phone_number_label': 'Telefone com código de área',
    'profile.security_title': 'Segurança',
    'profile.new_password_label': 'Nova Senha',
    'profile.confirm_password_label': 'Confirmar Nova Senha',
    'profile.update_password': 'ATUALIZAR SENHA',
    'profile.push_title': 'Notificações Push',
    'profile.push_description': 'Receba avisos importantes, novas aulas e atualizações da comunidade diretamente via notificações push.',
    'profile.status_support': 'Suporte',
    'profile.status_available': 'DISPONÍVEL',
    'profile.status_not_supported': 'NÃO SUPORTADO',
    'profile.status_permission': 'Permissão',
    'profile.permission_granted': 'CONCEDIDA',
    'profile.permission_denied': 'NEGADA',
    'profile.permission_default': 'PENDENTE',
    'profile.install_pwa_title': 'Notificações não suportadas',
    'profile.install_pwa_description': 'Para receber notificações no seu dispositivo, você precisa instalar o aplicativo.',
    'profile.install_pwa_button': 'INSTALAR APP',
    'profile.push_resync': 'RE-SINCRONIZAR NOTIFICAÇÕES',
    'push.title': 'Avisos Importantes!',
    'push.description': 'Deseja receber avisos de novas aulas, materiais e comunicados importantes diretamente no seu celular?',
    'push.allow': 'Ativar Notificações',
    'push.deny': 'Agora não',
    'push.success': 'Notificações ativadas com sucesso!',
    'push.blocked': 'Notificações bloqueadas no navegador. Redefina as permissões nas configurações do site.',
    'push.error': 'Não foi possível ativar. Verifique se você está em uma aba segura (HTTPS).',
    'notifications.title': 'Notificações',
    'notifications.clear_all': 'LIMPAR TUDO',
    'notifications.close': 'FECHAR PAINEL',
    'notifications.mark_as_read': 'marcar como lida',
    'notifications.empty': 'Você está em dia!',
    'notifications.empty_desc': 'Nenhuma notificação por aqui.',
    'course.questions_title': 'Dúvidas sobre a Aula',
    'course.question_placeholder': 'Qual é a sua dúvida?',
    'course.send_question': 'Enviar Dúvida',
    'course.no_questions': 'Nenhuma dúvida enviada ainda.',
    'course.admin_answer': 'Resposta do Expert',
    'course.question_sent': 'Dúvida enviada com sucesso! O expert responderá em breve.',
    'course.completed_lowercase': 'concluído',
    'course.waiting_answer': 'Aguardando Resposta',
    'course.answered_at': 'Respondido em',
    'admin.questions_tab': 'Dúvidas',
    'admin.questions_pending': 'Dúvidas Pendentes',
    'admin.reply_placeholder': 'Escreva sua resposta...',
    'admin.reply_send': 'Enviar Resposta',
    'admin.persona_name_required': 'Informe um nome para a persona',
    'admin.confirm_persona': 'CONFIRMAR PERSONA',
    'admin.change_persona': 'TROCAR PERSONA',
    'admin.persona_active': 'Persona ativa:',
    'admin.posting_as': 'Postando como',
    'admin.persona_name_placeholder': 'Nome do Autor (ex: Maria Silva)',
    'admin.notifications_community': 'Nova atividade na comunidade',
    'admin.notifications_question': 'Nova dúvida na aula',
    'notifications.user_answer': 'Sua dúvida foi respondida!',
    'notifications.user_comment': 'Novo comentário no seu post',
    'pwa.install_title': 'Instale nosso aplicativo 📲',
    'pwa.install_desc': 'Tenha acesso rápido, sem precisar abrir o navegador',
    'pwa.ios_label': 'Instale manualmente no seu iPhone',
    'pwa.android_label': 'Instale com um clique no seu Android',
    'pwa.mobile_header': 'Instale no seu celular para uma melhor experiência',
    'pwa.desktop_label': 'Instale direto no seu computador',
    'pwa.ios_step1': 'Toque no ícone de três pontos (⋯) no canto inferior direito',
    'pwa.ios_step2': 'Selecione a opção “Compartilhar”',
    'pwa.ios_step3': 'Toque em “Ver mais”',
    'pwa.ios_step4': 'Escolha “Adicionar à Tela de Início”',
    'pwa.ios_step5': 'Toque em “Adicionar” para confirmar',
    'pwa.android_step1': 'Clique no botão Instalar abaixo',
    'pwa.desktop_step1': 'Use o ícone na barra de endereços',
    'pwa.got_it': 'ENTENDI',
    'pwa.install_button': 'INSTALAR AGORA',
    'pwa.already_installed': 'JÁ INSTALEI',
    'pwa.install_app': '📲 Instalar App',
    'pwa.auto_slide_interval': '3',
    'pwa.steps.ios': '["Toque no ícone de três pontos (⋯) no canto inferior direito", "Selecione a opção “Compartilhar”", "Toque em “Ver mais”", "Escolha “Adicionar à Tela de Início”", "Toque em “Adicionar” para confirmar"]',
    'pwa.steps.android': '["Clique no botão Instalar abaixo"]',
    'pwa.steps.desktop': '["Use o ícone na barra de endereços"]',
    'dashboard.level_0': 'Novo Jogador',
    'dashboard.level_1': 'Iniciante',
    'dashboard.level_2': 'Aprendiz',
    'dashboard.level_3': 'Mestre',
    'dashboard.level_4': 'Elite',
    'dashboard.level_5': 'Lendário',
    'dashboard.progress_title': 'Progresso do Curso',
    'celebration.25': '🔥 Parabéns! Você já conquistou 25% do conteúdo! Continue assim!',
    'celebration.50': '⭐ Sensacional! Metade do caminho já foi! O topo está próximo!',
    'celebration.75': '🚀 Impressionante! 75% concluído. Você é pura determinação!',
    'celebration.100': '🏆 LENDÁRIO! 100% CONCLUÍDO! Você dominou todo o conteúdo! Parabéns!',
    'badge.locked': 'MÉTODO PREMIUM',
    'cta.unlock': 'ADQUIRIR AGORA',
    'badge.completed': 'CONCLUÍDO',
    'cta.completed': 'ASSISTIR NOVAMENTE',
    'badge.in_progress': 'CONTINUAR',
    'cta.in_progress': 'RETOMAR AULA',
    'badge.new': 'COMEÇAR',
    'cta.new': 'COMEÇAR AGORA',
    'course.progresso': 'Progresso',
    'course.exclusive_content': 'Conteúdo Exclusivo',
    'dashboard.resume_label': 'Comece de onde parou',
    'gamification.modal_title': 'NÍVEL: {level}',
    'gamification.progress_label': 'Seu progresso total atingiu {progress}%',
    'gamification.next_achievement': 'Próxima Conquista',
    'gamification.continue_journey': 'CONTINUAR JORNADA',
    'gamification.ranking_label': 'VER MEU RANKING',
    'gamification.level_up': 'LEVEL UP',
    'gamification.completed_status': '{progress}% CONCLUÍDO',
    'gamification.target_label': 'Objetivo Atual • Falta {left}% para o próximo level',
    'gamification.level_0_label': 'Novo Jogador',
    'gamification.level_1_label': 'Iniciante',
    'gamification.level_2_label': 'Aprendiz',
    'gamification.level_3_label': 'Mestre',
    'gamification.level_4_label': 'Elite',
    'gamification.level_5_label': 'Lendário',
    'gamification.level_0_req': 'Complete sua primeira aula',
    'gamification.level_1_req': 'Chegue a 25% de progresso total',
    'gamification.level_2_req': 'Chegue a 50% de progresso total',
    'gamification.level_3_req': 'Chegue a 75% de progresso total',
    'gamification.level_4_req': 'Conclua 100% dos conteúdos',
    'gamification.level_5_req': 'Você atingiu o topo!',
    'gamification.you_label': 'VOCÊ',
    'gamification.view_progress_tooltip': 'Ver Progresso & Medalhas',
    'course.preview_badge': 'PREVIEW',
    'dashboard.empty_all_unlocked': 'Você já possui todos os cursos disponíveis!',
    'dashboard.empty_locked': 'Você ainda não possui cursos liberados.',
  },
  en: {
    'auth.welcome_back': 'Welcome back!',
    'auth.subtitle': 'Access your exclusive area',
    'auth.login': 'Sign In',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.restricted_access': 'Restricted Access Notice',
    'auth.restricted_access_msg': 'Restricted access to registered users.',
    'auth.logout_success': 'See you soon!',
    'auth.master_password': 'Master Password',
    'auth.support_box': 'Need Support?',
    'auth.support_description': 'Our team is ready to help you with any questions or technical issues.',
    'auth.whatsapp_label': 'WhatsApp',
    'auth.email_label': 'Email',
    'auth.user_not_found': 'User not found',
    'auth.invalid_password': 'Incorrect password. Please verify and try again.',
    'auth.fill_this_field': 'Please fill this field',
    'auth.invalid_email': 'Please enter a valid email address',
    'auth.invalid_response': 'Server communication error. Please try again soon.',
    'auth.credentials_error': 'Failed to generate access credentials',
    'auth.generic_error': 'An error occurred. Please try again.',
    'auth.verify_access': 'Verify Access',
    'auth.admin_identified': 'Administrative access identified. Please enter the master password to continue.',
    'auth.disclaimer': 'By entering, you agree to our Terms of Use and Privacy Policy.',
    'global.logout_error': 'Error signing out',
    'global.logging_out': 'Logging out...',
    'global.session_lost': 'Session lost. Restarting...',
    'profile.update_error': 'Error updating profile',
    'profile.avatar_error': 'Error uploading profile picture',
    'profile.password_error': 'Error updating password',
    'dashboard.loading_error': 'Error loading content',
    'course.purchase_unavailable': 'This course does not have a purchase link configured yet.',
    'course.not_found': 'Course not found',
    'course.loading_error': 'Error loading course',
    'course.progress_error': 'Error updating progress',
    'course.module': 'Module',
    'course.video_lesson': 'Video Lesson',
    'course.pdf_material': 'PDF Material',
    'course.reading': 'Reading',
    'course.view_fullscreen': 'View Fullscreen',
    'push.new_notification': 'New Notification',
    'nav.home': 'Home',
    'nav.community': 'Community',
    'nav.profile': 'Profile',
    'nav.admin': 'Admin',
    'global.save': 'Save',
    'global.cancel': 'Cancel',
    'global.delete': 'Delete',
    'global.back': 'Back',
    'global.logout': 'Logout',
    'dashboard.courses_paid': 'My Courses  📚',
    'dashboard.courses_free': 'Accelerate your Evolution  🚀',
    'dashboard.courses_bonus': 'My Bonuses  🎁',
    'course.progress': 'Your Progress',
    'course.your_progress': 'Your Progress',
    'course.lessons': 'Lessons',
    'course.content': 'Content',
    'course.no_media': 'Lesson without media content',
    'course.lesson_completed': 'Lesson completed!',
    'course.progress_saved': 'Your progress has been saved successfully.',
    'course.prev_lesson': 'Previous Lesson',
    'course.next_lesson': 'Next Lesson',
    'course.materials': 'Materials',
    'course.lesson_unmarked': 'Lesson marked as not completed',
    'course.lesson_completed_btn': 'LESSON COMPLETED',
    'course.complete_lesson_btn': 'FINISH LESSON',
    'course.end_label': 'End',
    'course.support_description': 'Our team is ready to help you.',
    'course.premium_content': 'PREMIUM CONTENT',
    'course.unlock_button': 'UNLOCK ACCESS NOW',
    'course.secure_payment': '100% Secure Payment • Immediate Access',
    'course.schedule_title': 'Course Schedule',
    'course.completed': 'COMPLETED',
    'course.continue': 'CONTINUE',
    'course.start': 'START',
    'community.title': 'Community',
    'community.subtitle': 'Share your journey',
    'community.input_placeholder': 'What do you want to share?',
    'community.post': 'Post',
    'community.send_reply': 'Send Reply',
    'community.reply': 'Reply',
    'community.replying_to': 'In response to',
    'community.like': 'Like',
    'community.delete_post': 'Delete Post',
    'community.add_photo': 'Add Photo',
    'community.post_sent': 'Post sent!',
    'community.post_updated': 'Post updated!',
    'community.edit_post': 'Edit Post',
    'community.delete_post_confirm': 'Delete Post?',
    'community.delete_comment_confirm': 'Delete Comment?',
    'community.comment_placeholder': 'Write a comment...',
    'community.delete_post_desc': 'This action cannot be undone. The post and its image will be permanently removed.',
    'community.delete_comment_desc': 'The comment will be permanently removed.',
    'community.delete_success': 'Post deleted successfully!',
    'community.delete_error': 'Error deleting post',
    'community.load_error': 'Error loading posts',
    'community.create_error': 'Error sending post',
    'community.update_error': 'Error updating post',
    'community.upload_error': 'Could not upload photo. Check your connection.',
    'community.comment_error': 'Error sending comment',
    'community.comment_delete_success': 'Comment deleted successfully!',
    'community.comment_delete_error': 'Error deleting comment',
    'community.date_format': 'MMM d, h:mm a',
    'community.locale': 'enUS',
    'community.load_more': 'Load more posts',
    'community.loading_posts': 'Loading posts...',
    'profile.title': 'My Profile',
    'profile.subtitle': 'Manage your information',
    'profile.save_changes': 'Save Changes',
    'profile.change_password': 'Change Password',
    'profile.update_success': 'Profile updated successfully!',
    'profile.avatar_success': 'Profile picture updated!',
    'profile.password_mismatch': 'Passwords do not match',
    'profile.password_success': 'Password updated successfully!',
    'profile.change_photo': 'Change picture',
    'profile.info_title': 'User Information',
    'profile.access': 'Access',
    'profile.email_restricted': 'Email cannot be changed.',
    'profile.name_label': 'Name',
    'profile.name_placeholder': 'Your name',
    'profile.phone_label': 'Phone (WhatsApp)',
    'profile.phone_country_code': 'Country code',
    'profile.phone_number_label': 'Phone with area code',
    'profile.security_title': 'Security',
    'profile.new_password_label': 'New Password',
    'profile.confirm_password_label': 'Confirm New Password',
    'profile.update_password': 'UPDATE PASSWORD',
    'profile.push_title': 'Push Notifications',
    'profile.push_description': 'Receive important notices, new classes, and community updates directly via push notifications.',
    'profile.status_support': 'Support',
    'profile.status_available': 'AVAILABLE',
    'profile.status_not_supported': 'NOT SUPPORTED',
    'profile.status_permission': 'Permission',
    'profile.permission_granted': 'GRANTED',
    'profile.permission_denied': 'DENIED',
    'profile.permission_default': 'PENDING',
    'profile.install_pwa_title': 'Notifications not supported',
    'profile.install_pwa_description': 'To receive notifications on your device, you need to install the application.',
    'profile.install_pwa_button': 'INSTALL APP',
    'profile.push_resync': 'RE-SYNC NOTIFICATIONS',
    'push.title': 'Important Notifications!',
    'push.description': 'Would you like to receive notifications of new classes, materials, and important announcements directly on your phone?',
    'push.allow': 'Enable Notifications',
    'push.deny': 'Not now',
    'push.success': 'Notifications enabled successfully!',
    'push.blocked': 'Notifications blocked in browser. Reset permissions in site settings.',
    'push.error': 'Could not enable. Check if you are on a secure (HTTPS) tab.',
    'notifications.title': 'Notifications',
    'notifications.clear_all': 'CLEAR ALL',
    'notifications.close': 'CLOSE PANEL',
    'notifications.mark_as_read': 'mark as read',
    'notifications.empty': 'You are up to date!',
    'notifications.empty_desc': 'No notifications here.',
    'course.questions_title': 'Lesson Questions',
    'course.question_placeholder': 'What is your question?',
    'course.send_question': 'Send Question',
    'course.no_questions': 'No questions sent yet.',
    'course.admin_answer': 'Expert\'s Answer',
    'course.question_sent': 'Question sent successfully! The expert will answer soon.',
    'course.completed_lowercase': 'completed',
    'course.waiting_answer': 'Waiting for Answer',
    'course.answered_at': 'Answered on',
    'admin.questions_tab': 'Questions',
    'admin.questions_pending': 'Pending Questions',
    'admin.reply_placeholder': 'Write your answer...',
    'admin.reply_send': 'Send Answer',
    'admin.persona_name_required': 'Please enter a name for the persona',
    'admin.confirm_persona': 'CONFIRM PERSONA',
    'admin.change_persona': 'CHANGE PERSONA',
    'admin.persona_active': 'Persona active:',
    'admin.posting_as': 'Posting as',
    'admin.persona_name_placeholder': 'Author Name (e.g. Maria Silva)',
    'admin.notifications_community': 'New community activity',
    'admin.notifications_question': 'New lesson question',
    'notifications.user_answer': 'Your question has been answered!',
    'notifications.user_comment': 'New comment on your post',
    'pwa.install_title': 'Install our app 📲',
    'pwa.install_desc': 'Get fast access, without opening the browser',
    'pwa.ios_label': 'Install manually on your iPhone',
    'pwa.android_label': 'Install with one click on your Android',
    'pwa.mobile_header': 'Install on your phone for a better experience',
    'pwa.desktop_label': 'Install directly on your computer',
    'pwa.ios_step1': 'Tap the three dots (⋯) in the bottom right corner',
    'pwa.ios_step2': 'Select “Share”',
    'pwa.ios_step3': 'Tap “More”',
    'pwa.ios_step4': 'Choose “Add to Home Screen”',
    'pwa.ios_step5': 'Tap “Add” to confirm',
    'pwa.android_step1': 'Click the Install button below',
    'pwa.desktop_step1': 'Use the icon in the address bar',
    'pwa.got_it': 'GOT IT',
    'pwa.install_button': 'INSTALL NOW',
    'pwa.already_installed': 'ALREADY INSTALLED',
    'pwa.install_app': '📲 Install App',
    'pwa.steps.ios': '["Tap the three dots (⋯) in the bottom right corner", "Select “Share”", "Tap “More”", "Choose “Add to Home Screen”", "Tap “Add” to confirm"]',
    'pwa.steps.android': '["Click the Install button below"]',
    'pwa.steps.desktop': '["Use the icon in the address bar"]',
    'dashboard.level_0': 'New Player',
    'dashboard.level_1': 'Beginner',
    'dashboard.level_2': 'Apprentice',
    'dashboard.level_3': 'Master',
    'dashboard.level_4': 'Elite',
    'dashboard.level_5': 'Legendary',
    'dashboard.progress_title': 'Course Progress',
    'celebration.25': '🔥 Congratulations! You have conquered 25% of the content! Keep it up!',
    'celebration.50': '⭐ Sensational! Halfway there! The top is near!',
    'celebration.75': '🚀 Impressive! 75% completed. You are pure determination!',
    'celebration.100': '🏆 LEGENDARY! 100% COMPLETED! You mastered all the content! Congratulations!',
    'badge.locked': 'PREMIUM METHOD',
    'cta.unlock': 'BUY NOW',
    'badge.completed': 'COMPLETED',
    'cta.completed': 'WATCH AGAIN',
    'badge.in_progress': 'CONTINUE',
    'cta.in_progress': 'RESUME LESSON',
    'badge.new': 'START',
    'cta.new': 'START NOW',
    'course.progresso': 'Progress',
    'course.exclusive_content': 'Exclusive Content',
    'gamification.modal_title': 'LEVEL: {level}',
    'gamification.progress_label': 'Your total progress has reached {progress}%',
    'gamification.next_achievement': 'Next Achievement',
    'gamification.continue_journey': 'CONTINUE JOURNEY',
    'gamification.ranking_label': 'VIEW MY RANKING',
    'gamification.level_up': 'LEVEL UP',
    'gamification.target_label': 'Current Objective • {left}% left for next level',
    'gamification.level_short': 'Lvl',
    'gamification.level_0_label': 'New Player',
    'gamification.level_1_label': 'Beginner',
    'gamification.level_2_label': 'Apprentice',
    'gamification.level_3_label': 'Master',
    'gamification.level_4_label': 'Elite',
    'gamification.level_5_label': 'Legendary',
    'gamification.level_0_req': 'Complete your first lesson',
    'gamification.level_1_req': 'Reach 25% total progress',
    'gamification.level_2_req': 'Reach 50% total progress',
    'gamification.level_3_req': 'Reach 75% total progress',
    'gamification.level_4_req': 'Complete 100% of the content',
    'gamification.level_5_req': 'You have reached the top!',
    'gamification.you_label': 'YOU',
    'gamification.view_progress_tooltip': 'View Progress & Badges',
    'course.preview_badge': 'PREVIEW',
    'dashboard.empty_all_unlocked': 'You already have all available courses!',
    'dashboard.empty_locked': 'You do not have any unlocked courses yet.',
  },
  es: {
    'auth.welcome_back': '¡Bienvenido de nuevo!',
    'auth.subtitle': 'Accede a tu área exclusiva',
    'auth.login': 'Entrar',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.restricted_access': 'Aviso de Acceso Restringido',
    'auth.restricted_access_msg': 'Acceso restringido a usuarios registrados.',
    'auth.logout_success': '¡Hasta pronto!',
    'auth.master_password': 'Password Maestra',
    'auth.support_box': '¿Necesitas Ayuda?',
    'auth.support_description': 'Nuestro equipo está listo para ayudarte con cualquier duda o problema técnico.',
    'auth.whatsapp_label': 'WhatsApp',
    'auth.email_label': 'Correo',
    'auth.user_not_found': 'Usuario no encontrado',
    'auth.invalid_password': 'Contraseña incorrecta. Por favor, verifique e intente de nuevo.',
    'auth.fill_this_field': 'Por favor, completa este campo',
    'auth.invalid_email': 'Por favor, ingrese un correo electrónico válido',
    'auth.invalid_response': 'Error de comunicación con el servidor. Inténtelo de nuevo pronto.',
    'auth.credentials_error': 'Error al generar credenciales de acceso',
    'auth.generic_error': 'Ocurrió un error. Inténtelo de nuevo.',
    'auth.verify_access': 'Verificar Acceso',
    'auth.admin_identified': 'Se ha identificado un acceso administrativo. Por favor, introduzca la contraseña maestra para continuar.',
    'auth.disclaimer': 'Al entrar, aceptas nuestros Términos de Uso y Política de Privacidad.',
    'global.logout_error': 'Error al cerrar la sesión',
    'global.logging_out': 'Cerrando sesión...',
    'global.session_lost': 'Sesión perdida. Reiniciando...',
    'profile.update_error': 'Error al actualizar el perfil',
    'profile.avatar_error': 'Error al subir la foto de perfil',
    'profile.password_error': 'Error al actualizar la contraseña',
    'dashboard.loading_error': 'Error al cargar el contenido',
    'course.purchase_unavailable': 'Este curso aún no tiene configurado un enlace de compra.',
    'course.not_found': 'Curso no encontrado',
    'course.loading_error': 'Error al cargar el curso',
    'course.progress_error': 'Error al actualizar el progreso',
    'course.module': 'Módulo',
    'course.video_lesson': 'Video lección',
    'course.pdf_material': 'Material PDF',
    'course.reading': 'Lectura',
    'course.view_fullscreen': 'Ver en Pantalla Completa',
    'push.new_notification': 'Nueva Notificación',
    'nav.home': 'Inicio',
    'nav.community': 'Comunidad',
    'nav.profile': 'Perfil',
    'nav.admin': 'Admin',
    'global.save': 'Guardar',
    'global.cancel': 'Cancelar',
    'global.delete': 'Eliminar',
    'global.back': 'Volver',
    'global.logout': 'Salir',
    'dashboard.courses_paid': 'Mis Cursos  📚',
    'dashboard.courses_free': 'Acelere su Evolución  🚀',
    'dashboard.courses_bonus': 'Mis Bonos  🎁',
    'course.progress': 'Tu Progreso',
    'course.your_progress': 'Tu Progresso',
    'course.lessons': 'Lecciones',
    'course.content': 'Contenido',
    'course.no_media': 'Lección sin contenido multimedia',
    'course.lesson_completed': '¡Lección completada!',
    'course.progress_saved': 'Your progress has been saved successfully.',
    'course.prev_lesson': 'Lección Anterior',
    'course.next_lesson': 'Próxima Lección',
    'course.materials': 'Materiales',
    'course.lesson_unmarked': 'Lección marcada como no finalizada',
    'course.lesson_completed_btn': 'LECCIÓN COMPLETADA',
    'course.complete_lesson_btn': 'FINALIZAR LECCIÓN',
    'course.end_label': 'Fin',
    'course.support_description': 'Nuestro equipo está listo para ayudarte.',
    'course.premium_content': 'CONTENIDO PREMIUM',
    'course.unlock_button': 'LIBERAR ACCESO AHORA',
    'course.secure_payment': 'Pago 100% Seguro • Acceso Inmediato',
    'course.schedule_title': 'Cronograma del Curso',
    'course.completed': 'COMPLETADO',
    'course.continue': 'CONTINUAR',
    'course.start': 'COMENZAR',
    'community.title': 'Comunidad',
    'community.subtitle': 'Comparte tu jornada',
    'community.input_placeholder': '¿Qué quieres compartir?',
    'community.post': 'Publicar',
    'community.send_reply': 'Enviar Respuesta',
    'community.reply': 'Responder',
    'community.replying_to': 'En respuesta a',
    'community.like': 'Me gusta',
    'community.delete_post': 'Eliminar Publicación',
    'community.add_photo': 'Agregar foto',
    'community.post_sent': '¡Post enviado!',
    'community.post_updated': '¡Post actualizado!',
    'community.edit_post': 'Editar Publicación',
    'community.delete_post_confirm': '¿Eliminar Publicación?',
    'community.delete_comment_confirm': '¿Eliminar Comentario?',
    'community.comment_placeholder': 'Escribe un comentario...',
    'community.delete_post_desc': 'Esta acción no se puede deshacer. La publicación y su imagen se eliminarán permanentemente.',
    'community.delete_comment_desc': 'El comentario se eliminará permanentemente.',
    'community.delete_success': '¡Publicación eliminada con éxito!',
    'community.delete_error': 'Error al eliminar publicación',
    'community.load_error': 'Error al cargar publicaciones',
    'community.create_error': 'Error al enviar publicación',
    'community.update_error': 'Error al actualizar publicación',
    'community.upload_error': 'No se pudo subir la foto. Verifique su conexión.',
    'community.comment_error': 'Error al enviar comentario',
    'community.comment_delete_success': '¡Comentario eliminado con éxito!',
    'community.comment_delete_error': 'Error al eliminar comentario',
    'community.date_format': 'd MMM, HH:mm',
    'community.locale': 'es',
    'community.load_more': 'Cargar más publicaciones',
    'community.loading_posts': 'Cargando publicaciones...',
    'profile.title': 'Mi Perfil',
    'profile.subtitle': 'Gestiona tu información',
    'profile.save_changes': 'Guardar Cambios',
    'profile.change_password': 'Cambiar Contraseña',
    'profile.update_success': '¡Perfil actualizado con éxito!',
    'profile.avatar_success': '¡Foto de perfil actualizada!',
    'profile.password_mismatch': 'Las contraseñas no coinciden',
    'profile.password_success': '¡Contraseña actualizada con éxito!',
    'profile.change_photo': 'Cambiar foto',
    'profile.info_title': 'Información del Usuario',
    'profile.access': 'Acceso',
    'profile.email_restricted': 'El correo electrónico no se puede cambiar.',
    'profile.name_label': 'Nombre',
    'profile.name_placeholder': 'Tu nombre',
    'profile.phone_label': 'Teléfono (WhatsApp)',
    'profile.phone_country_code': 'Código de país',
    'profile.phone_number_label': 'Teléfono con código de área',
    'profile.security_title': 'Seguridad',
    'profile.new_password_label': 'Nueva Contraseña',
    'profile.confirm_password_label': 'Confirmar Nueva Contraseña',
    'profile.update_password': 'ACTUALIZAR CONTRASEÑA',
    'profile.push_title': 'Notificaciones Push',
    'profile.push_description': 'Reciba avisos importantes, nuevas clases y actualizaciones de la comunidad directamente vía notificaciones push.',
    'profile.status_support': 'Soporte',
    'profile.status_available': 'DISPONIBLE',
    'profile.status_not_supported': 'NO SOPORTADO',
    'profile.status_permission': 'Permiso',
    'profile.permission_granted': 'CONCEDIDA',
    'profile.permission_denied': 'NEGADA',
    'profile.permission_default': 'PENDIENTE',
    'profile.install_pwa_title': 'Notificaciones no soportadas',
    'profile.install_pwa_description': 'Para recibir notificaciones en su dispositivo, debe instalar la aplicación.',
    'profile.install_pwa_button': 'INSTALAR APP',
    'profile.push_resync': 'RE-SINCRO NOTIFICACIONES',
    'push.title': '¡Avisos Importantes!',
    'push.description': '¿Deseas recibir avisos de nuevas clases, materiales y comunicados importantes directamente en tu celular?',
    'push.allow': 'Activar Notificaciones',
    'push.deny': 'Ahora no',
    'push.success': '¡Notificaciones activadas con éxito!',
    'push.blocked': 'Notificaciones bloqueadas en el navegador. Restablezca los permisos en la configuración del sitio.',
    'push.error': 'No se pudo activar. Verifique si está en una pestaña segura (HTTPS).',
    'notifications.title': 'Notificaciones',
    'notifications.clear_all': 'LIMPIAR TODO',
    'notifications.close': 'CERRAR PANEL',
    'notifications.mark_as_read': 'marcar como leída',
    'notifications.empty': '¡Estás al día!',
    'notifications.empty_desc': 'No hay notificaciones por aquí.',
    'course.questions_title': 'Dudas sobre la Lección',
    'course.question_placeholder': '¿Cuál es tu duda?',
    'course.send_question': 'Enviar Duda',
    'course.no_questions': 'Aún no hay dudas.',
    'course.admin_answer': 'Respuesta del Experto',
    'course.question_sent': '¡Duda enviada con éxito! El experto responderá pronto.',
    'course.completed_lowercase': 'completado',
    'course.waiting_answer': 'Esperando Respuesta',
    'course.answered_at': 'Respondido el',
    'admin.questions_tab': 'Dudas',
    'admin.questions_pending': 'Dudas Pendientes',
    'admin.reply_placeholder': 'Escribe tu respuesta...',
    'admin.reply_send': 'Enviar Respuesta',
    'admin.persona_name_required': 'Ingrese un nombre para la persona',
    'admin.confirm_persona': 'CONFIRMAR PERSONA',
    'admin.change_persona': 'CAMBIAR PERSONA',
    'admin.persona_active': 'Persona activa:',
    'admin.posting_as': 'Publicando como',
    'admin.persona_name_placeholder': 'Nombre del Autor (ej: Maria Silva)',
    'admin.notifications_community': 'Nueva actividad en la comunidad',
    'admin.notifications_question': 'Nueva duda en la lección',
    'notifications.user_answer': '¡Tu duda ha sido respondida!',
    'notifications.user_comment': 'Nuevo comentario en tu post',
    'pwa.install_title': 'Instala nuestra app 📲',
    'pwa.install_desc': 'Ten acceso rápido, sin abrir el navegador',
    'pwa.ios_label': 'Instala manualmente en tu iPhone',
    'pwa.android_label': 'Instala con un clic en tu Android',
    'pwa.mobile_header': 'Instala en tu móvil para una mejor experiencia',
    'pwa.desktop_label': 'Instala directo en tu ordenador',
    'pwa.ios_step1': 'Toca el ícono de tres puntos (⋯) en la esquina inferior derecha',
    'pwa.ios_step2': 'Selecciona “Compartir”',
    'pwa.ios_step3': 'Toca “Ver más”',
    'pwa.ios_step4': 'Elige “Agregar a pantalla de inicio”',
    'pwa.ios_step5': 'Toca “Agregar” para confirmar',
    'pwa.android_step1': 'Haz clic en el botón Instalar abajo',
    'pwa.desktop_step1': 'Usa el icono en la barra de direcciones',
    'pwa.got_it': 'ENTENDIDO',
    'pwa.install_button': 'INSTALAR AHORA',
    'pwa.already_installed': 'YA INSTALÉ',
    'pwa.install_app': '📲 Instalar App',
    'pwa.steps.ios': '["Toca el ícono de tres puntos (⋯) en la esquina inferior derecha", "Selecciona “Compartir”", "Toca “Ver más”", "Elige “Agregar a pantalla de inicio”", "Toca “Agregar” para confirmar"]',
    'pwa.steps.android': '["Haz clic en el botão Instalar abajo"]',
    'pwa.steps.desktop': '["Usa el icono en la barra de direcciones"]',
    'dashboard.level_0': 'Nuevo Jugador',
    'dashboard.level_1': 'Principiante',
    'dashboard.level_2': 'Aprendiz',
    'dashboard.level_3': 'Maestro',
    'dashboard.level_4': 'Elite',
    'dashboard.level_5': 'Legendario',
    'dashboard.progress_title': 'Progreso del Curso',
    'celebration.25': '🔥 ¡Felicidades! ¡Ya has conquistado el 25% del contenido! ¡Sigue así!',
    'celebration.50': '⭐ ¡Sensacional! ¡Ya estás a mitad de camino! ¡La cima está cerca!',
    'celebration.75': '🚀 ¡Impresionante! 75% completado. ¡Eres pura determinación!',
    'celebration.100': '🏆 ¡LEGENDARIO! ¡100% COMPLETADO! ¡Has dominado todo el contenido! ¡Felicidades!',
    'badge.locked': 'MÉTODO PREMIUM',
    'cta.unlock': 'ADQUIRIR AHORA',
    'badge.completed': 'COMPLETADO',
    'cta.completed': 'VER DE NUEVO',
    'badge.in_progress': 'CONTINUAR',
    'cta.in_progress': 'REANUDAR CLASE',
    'badge.new': 'COMENZAR',
    'cta.new': 'COMENZAR AHORA',
    'course.progresso': 'Progreso',
    'course.exclusive_content': 'Contenido Exclusivo',
    'gamification.modal_title': 'NIVEL: {level}',
    'gamification.progress_label': 'Tu progreso total ha alcanzado el {progress}%',
    'gamification.next_achievement': 'Próximo Logro',
    'gamification.continue_journey': 'CONTINUAR JORNADA',
    'gamification.ranking_label': 'VER MI RANKING',
    'gamification.level_up': 'LEVEL UP',
    'gamification.target_label': 'Objetivo Actual • Falta {left}% para el próximo nivel',
    'gamification.level_short': 'Nivel',
    'gamification.level_0_label': 'Nuevo Jugador',
    'gamification.level_1_label': 'Principiante',
    'gamification.level_2_label': 'Aprendiz',
    'gamification.level_3_label': 'Maestro',
    'gamification.level_4_label': 'Elite',
    'gamification.level_5_label': 'Legendario',
    'gamification.level_0_req': 'Completa tu primera lección',
    'gamification.level_1_req': 'Llega al 25% de progreso total',
    'gamification.level_2_req': 'Llega al 50% de progreso total',
    'gamification.level_3_req': 'Llega al 75% de progreso total',
    'gamification.level_4_req': 'Completa el 100% de los contenidos',
    'gamification.level_5_req': '¡Has llegado a la cima!',
    'gamification.you_label': 'TÚ',
    'gamification.view_progress_tooltip': 'Ver Progreso y Medallas',
    'course.preview_badge': 'VISTA PREVIA',
    'dashboard.empty_all_unlocked': '¡Ya tienes todos los cursos disponibles!',
    'dashboard.empty_locked': 'Aún no tienes cursos liberados.',
  }
};
